"""Remove IP address in user

Revision ID: 072ccbcc7bd4
Revises: 11525e42c26d
Create Date: 2026-06-09 01:08:09.338273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '072ccbcc7bd4'
down_revision: Union[str, Sequence[str], None] = '11525e42c26d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('user_ip_address_key'), 'user', type_='unique')
    op.drop_column('user', 'ip_address')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('ip_address', sa.VARCHAR(length=128), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('user_ip_address_key'), 'user', ['ip_address'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
