import json
import logging

from secrets import token_urlsafe

from sqlalchemy import select
from sqlalchemy.orm import Session

from db.db_session import SessionLocal
from db.models.core import User, Profile, ProfileSubscription, Subscription, Url
from db.models.enum.subscription import SubscriptionEnum

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

def seed_subscriptions(session: Session):
    """Populates the base subscription tiers if they don't exist."""
    logger.info("Seeding subscriptions...")

    with open('db/seed/raw/subscriptions.json', 'r', encoding='utf-8') as file:
        tiers = json.load(file)
        for tier in tiers:
            sub_name = SubscriptionEnum(tier["name"])
            existing = session.scalar(
                select(Subscription).where(Subscription.name == sub_name)
            )
            if not existing:
                new_sub = Subscription(**{
                    **tier,
                    "name": sub_name
                })
                session.add(new_sub)
                logger.info(f"Added subscription tier: {sub_name}")
            else:
                logger.info(f"Subscription tier {sub_name} already exists. Skipping.")

def seed_test_users(session: Session):
    """Seeds a test user with a profile and an assigned subscription tier."""
    logger.info("Seeding test users...")

    with open('db/seed/raw/users.json', 'r', encoding='utf-8') as file:
        users = json.load(file)

        for user in users:
            # Check if our default user exists
            existing_user = session.scalar(select(User).where(User.username == user["username"]))
            if existing_user:
                logger.info("User '%s' already exists. Skipping.", user["username"])
                return

            # 1. Create the base User
            new_user = User(
                username=user["username"],
                # This calls your custom setter method under the hood to automatically hash it
                password=user["password"]
            )
            session.add(new_user)
            session.flush()  # Flushes to get the admin_user.id generated by Postgres

            profile = user.get("profile", {})
            # 2. Create the associated Profile
            new_profile = Profile(
                name=profile["name"],
                profile_img=profile["profile_img"],
                user_id=new_user.id
            )
            session.add(new_profile)
            session.flush()  # Flushes to get the admin_profile.id

            subscription = profile.get("subscription", {})

            # 3. Fetch the the correct Subscription tier to link it
            profile_sub = session.scalar(
                select(Subscription).where(Subscription.name == SubscriptionEnum(subscription["subscription_name"]))
            )
    
            if profile_sub:
                # Create the historic snapshot link in user_subscription table
                user_sub_link = ProfileSubscription(
                    profile_id=new_profile.id,
                    subscription_id=profile_sub.id,
                    limit=profile_sub.limit,
                    price=profile_sub.price
                )
                session.add(user_sub_link)
            
            url_list = profile.get("url", [])
            for url in url_list:
                # 4. Give them an initial shortened URL
                sample_url = Url(
                    creator_ip=url.get("creator_ip", ""),
                    mapped_url_id=token_urlsafe(16),
                    original_url=url.get("original_url", ""),
                    profile_id=new_profile.id
                )
                session.add(sample_url)
    
    session.commit()
    logger.info("Successfully seeded 'admin' account with complete profile architecture.")

def run_seeder():
    """Main execution point wrapped in a transactional session context."""
    with SessionLocal() as session:
        try:
            seed_subscriptions(session)
            session.flush() # Ensure subscriptions exist before linking them to profiles
            
            seed_test_users(session)
            
            session.commit()
            logger.info("Database seeding completed successfully!")
        except Exception as e:
            session.rollback()
            logger.error(f"Seeding failed! Rolling back changes. Error: {e}")
            raise

if __name__ == "__main__":
    run_seeder()